spring.application.name=backend
server.port=8081

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver



# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Spring Security default behavior customization (Optional for layer 1)
# For now, let's keep default security which protects all endpoints

# JWT Security
jwt.secret=${JWT_SECRET}
